const CONFIG = { MESSAGES:'Mensajes', USERS:'Usuarios', MAX_MESSAGES:120 };
function doGet(){ setupSheets_(); return HtmlService.createHtmlOutputFromFile('Index').setTitle('RetroTalk 2000'); }
function setupSheets_(){
 const ss=SpreadsheetApp.getActive();
 let m=ss.getSheetByName(CONFIG.MESSAGES); if(!m){m=ss.insertSheet(CONFIG.MESSAGES);m.appendRow(['id','timestamp','senderEmail','senderName','recipientEmail','text']);m.setFrozenRows(1)}
 let u=ss.getSheetByName(CONFIG.USERS); if(!u){u=ss.insertSheet(CONFIG.USERS);u.appendRow(['email','displayName','lastSeen']);u.setFrozenRows(1)}
}
function identity_(){const email=Session.getActiveUser().getEmail();if(!email)throw new Error('No se pudo identificar al usuario. Despliega la web app para usuarios del dominio.');return {email,name:email.split('@')[0].replace(/[._-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}}
function bootstrap(){setupSheets_();const me=identity_();touch_(me);return {me,users:getUsers(),messages:[]}}
function touch_(me){const sh=SpreadsheetApp.getActive().getSheetByName(CONFIG.USERS),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(v[i][0]===me.email){sh.getRange(i+1,2,1,2).setValues([[me.name,new Date()]]);return}sh.appendRow([me.email,me.name,new Date()])}
function getUsers(){const me=identity_(),sh=SpreadsheetApp.getActive().getSheetByName(CONFIG.USERS),cut=Date.now()-45000;return sh.getDataRange().getValues().slice(1).filter(r=>r[0]&&r[0]!==me.email).map(r=>({email:r[0],name:r[1],online:new Date(r[2]).getTime()>=cut})).sort((a,b)=>Number(b.online)-Number(a.online)||a.name.localeCompare(b.name))}
function getConversation(otherEmail,afterIso){const me=identity_();touch_(me);const sh=SpreadsheetApp.getActive().getSheetByName(CONFIG.MESSAGES),last=sh.getLastRow();if(last<2)return {messages:[],users:getUsers()};const start=Math.max(2,last-CONFIG.MAX_MESSAGES+1),after=afterIso?new Date(afterIso).getTime():0;const rows=sh.getRange(start,1,last-start+1,6).getValues();const messages=rows.filter(r=>((r[2]===me.email&&r[4]===otherEmail)||(r[2]===otherEmail&&r[4]===me.email))&&new Date(r[1]).getTime()>after).map(r=>({id:r[0],timestamp:new Date(r[1]).toISOString(),senderEmail:r[2],senderName:r[3],recipientEmail:r[4],text:r[5]}));return {messages,users:getUsers()}}
function sendPrivateMessage(recipientEmail,text){const me=identity_();text=String(text||'').trim();if(!recipientEmail)throw new Error('Selecciona un contacto.');if(!text)throw new Error('El mensaje está vacío.');if(text.length>1000)throw new Error('Máximo 1000 caracteres.');touch_(me);const lock=LockService.getScriptLock();lock.waitLock(10000);try{const id=Utilities.getUuid(),now=new Date();SpreadsheetApp.getActive().getSheetByName(CONFIG.MESSAGES).appendRow([id,now,me.email,me.name,recipientEmail,text]);return {id,timestamp:now.toISOString(),senderEmail:me.email,senderName:me.name,recipientEmail,text}}finally{lock.releaseLock()}}
